### ISSUE TITLE
Undefined method `is_a_path?' for #<Bundler::Source::Path> with Bundler 1.16.x

### ISSUE THREAD

**Issue by garettarrowood** [powerhome/cobra_commander#16]
Building the component tree breaks with Bundler version 1.16.x.  It works fine with Bundle 1.15.3 on down.

```
Traceback (most recent call last):

	15: from bin/cobra:17:in `<main>'

	14: from bin/cobra:17:in `load'

	13: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/exe/cobra:6:in `<top (required)>'

	12: from /usr/local/rvm/gems/ruby-2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'

	11: from /usr/local/rvm/gems/ruby-2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'

	10: from /usr/local/rvm/gems/ruby-2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'

	 9: from /usr/local/rvm/gems/ruby-2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'

	 8: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/cli.rb:21:in `graph'

	 7: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/cli.rb:21:in `new'

	 6: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/graph.rb:11:in `initialize'

	 5: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/component_tree.rb:13:in `to_h'

	 4: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/component_tree.rb:33:in `to_h'

	 3: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/component_tree.rb:47:in `dependencies'

	 2: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/component_tree.rb:67:in `dependencies'

	 1: from /usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/component_tree.rb:67:in `select'

/usr/local/rvm/gems/ruby-2.5.0/gems/cobra_commander-0.3.0/lib/cobra_commander/component_tree.rb:68:in `block in dependencies': undefined method `is_a_path?' for #<Bundler::Source::Path:0x24618220 source at `components`> (NoMethodError)
```

**Comment by garettarrowood** [comment]
Resolved by #19
